version: "3.8"

services:
  database:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5051:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sampahku
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -d sampahku
      interval: 10s
      timeout: 3s
      retries: 5
  golang-sampahku:
    image: sampahku-api/1.0.0
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

volumes:
  postgres_data: